-d C:\Users\koenv\Documents\Github\gowin\hdmi_test\impl\gwsynthesis\hdmi_test.vg
-p GW5AT-60B-PBGA484A-1
-pn GW5AT-LV60PG484AC1/I0
-cst C:\Users\koenv\Documents\Github\gowin\hdmi_test\src\hdmi_top.cst
-cfg C:\Users\koenv\Documents\Github\gowin\hdmi_test\impl\pnr\device.cfg
-sdc C:\Users\koenv\Documents\Github\gowin\hdmi_test\src\hdmi_top.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
-enable_dsrm 0
